---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: partner
    test-network-function.com/generic: orchestrator
  annotations:
    test-network-function.com/defaultnetworkinterface: "\"eth0\"" # optional
  name: partner
  namespace: tnf
spec:
  containers:
    - command:
        - tail
        - -f
        - /dev/null
      image: quay.io/testnetworkfunction/cnf-test-partner:latest
      name: partner
      resources:
        limits:
          memory: 512Mi
          cpu: 0.25
  restartPolicy: Always
