---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test
    test-network-function.com/generic: target
    test-network-function.com/container: target
  annotations:
    test-network-function.com/container_tests: "[\"PRIVILEGED_POD\",\"PRIVILEGED_ROLE\"]" # optional
    test-network-function.com/defaultnetworkinterface: "\"eth0\"" # optional
  name: test
  namespace: tnf
spec:
  containers:
    - command:
        - tail
        - -f
        - /dev/null
      image: quay.io/testnetworkfunction/cnf-test-partner:latest
      name: test
      resources:
        limits:
          memory: 512Mi
          cpu: 0.25
  restartPolicy: Always
